const DATA={
A:{name:'Treino A',desc:'Peito, ombros e tríceps',mob:'Mobilidade de ombros',ex:[
['Supino inclinado com halteres ou máquina',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']]],
['Supino reto com halteres ou máquina',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']], '2 rest pause de 10 segundos na última série'],
['Supino declinado barra ou máquina',[['Ajuste','1','4–6','1–2 min'],['Trabalho','2','6–10','2 min']]],
['Voador com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','10–15','1 min']], '1 drop set na última série'],
['Elevação frontal',[['Ajuste','1','4–6','1–2 min'],['Trabalho','2','6–10','2 min']]],
['Elevação lateral sentado com halteres',[['Ajuste','1–2','4–6','1 min'],['Trabalho','2','8–12','1 min']], '1 drop set na última série'],
['Tríceps francês na corda',[['Ajuste','1','4–6','1–2 min'],['Trabalho','3','6–10','2 min']]]]},
B:{name:'Treino B',desc:'Costas e bíceps',mob:'Mobilidade de ombros e alongamento peito',ex:[
['Remada curvada com barra com 2 segundos de pico de contração',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']]],
['Remada baixa triângulo com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']], '2 rest pause de 10 segundos na última série'],
['Remada baixa pegada aberta ou máquina pegada aberta com 2 segundos de pico de contração',[['Ajuste','1','4–6','1–2 min'],['Trabalho','2','6–10','2 min']]],
['Pulley frente triângulo com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','8–12','2 min']], '1 drop set na última série'],
['Meio Terra',[['Aquecimento','1','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']]],
['Hiper extensão no banco romano',[['Trabalho','3','10–15','90 s']]],
['Rosca scott máquina com 2 segundos de pico de contração',[['Ajuste','1','4–6','1–2 min'],['Trabalho','3','6–10','2 min']]]]},
C:{name:'Treino C',desc:'Membros inferiores',mob:'Mobilidade e alongamento posteriores de coxa, glúteos, quadríceps e ílio-psoas',ex:[
['Agachamento livre',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']]],
['Leg 45',[['Ajuste','1','4–6','1–2 min'],['Trabalho','2','8–12','2–3 min']], '2 rest pause de 10 segundos na última série'],
['Extensor com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','10–15','1 min']]],
['Flexor deitado com 2 segundos de pico de contração',[['Aquecimento','1','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']]],
['Stiff',[['Aquecimento','1','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','8–10','2–3 min']]],
['Elevação de quadril com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']], '1 drop set na última série'],
['Panturrilha em pé na máquina ou no smith com 2 segundos de pico de contração',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','3','10–15','2 min']]]]},
D:{name:'Treino D',desc:'Ombros, estímulo em peito e tríceps',mob:'Mobilidade e alongamento ombros e tríceps',ex:[
['Desenvolvimento com halteres',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']]],
['Elevação frontal',[['Ajuste','1–2','4–6','1 min'],['Trabalho','2','10–15','1 min']], '2 rest pause de 10 segundos na última série'],
['Elevação lateral sentado com halteres',[['Ajuste','1–2','4–6','1 min'],['Trabalho','2','8–12','1 min']]],
['Elevação lateral máquina ou unilateral no cabo',[['Ajuste','1','4–6','1 min'],['Trabalho','2','8–12','1 min']], '1 drop set na última série'],
['Voador com 2 segundos de pico de contração',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','3','6–10','2–3 min']]],
['Tríceps corda com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','3','6–10','2 min']]],
['Tríceps testa corda banco 35 graus',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','3','8–12','2 min']], '2 rest pause de 10 segundos'] ]},
E:{name:'Treino E',desc:'Bíceps, costas e abdômen',mob:'Mobilidade de ombros e alongamento peito',ex:[
['Rosca direta cabo com 2 segundos de pico de contração',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2–3 min']]],
['Rosca scott máquina ou no cabo com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','8–12','2 min']], '2 rest pause de 10 segundos na última série'],
['Rosca direta corda',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','10–15','1 min']], '1 drop na última série'],
['Pulley frente aberto com 2 segundos de pico de contração',[['Aquecimento','1–2','10–15','1 min'],['Ajuste','1–2','4–6','1–2 min'],['Trabalho','3','8–12','2 min']]],
['Pulley frente triângulo com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','3','8–12','2 min']], '1 drop na última série'],
['Serrote com 2 segundos de pico de contração',[['Ajuste','1–2','4–6','1–2 min'],['Trabalho','2','6–10','2 min']]],
['Abdominal infra na torre com 2 segundos de pico de contração',[['Trabalho','3','RM','45 s']], '3x RM (máximo de repetições possíveis), intervalo 1 min'],
['Abdominal supra na prancha declinada',[['Trabalho','3','RM','45 s']], '3x RM (máximo de repetições possíveis), intervalo 1 min'] ]}
};
const KEY='treino_pro_v2';let db=JSON.parse(localStorage.getItem(KEY)||'null')||{history:[],drafts:{},custom:{}};if(db.config)Object.assign(DATA,db.config);const persistConfig=()=>{db.config=DATA;save()};let screen='home',current=null,timer=0,timerId=null,workStart=null;const app=document.getElementById('app');const save=()=>localStorage.setItem(KEY,JSON.stringify(db));const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t){let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),1800)}
function header(title,back=true){return `<div class="top"><div class="brand">TREINO PRO</div><button class="iconbtn" onclick="${back?'goHome()':'goSettings()'}">${back?'‹':'⚙'}</button></div><h1 class="screen-title">${title}</h1>`}
function home(){screen='home';app.innerHTML=`<div class="app">${header('Escolha seu treino',false)}<p class="muted">Selecione o treino do dia. Segunda A · Terça B · Quarta C · Quinta descanso · Sexta D · Sábado E · Domingo descanso.</p><div class="grid" style="margin-top:15px">${Object.entries(DATA).map(([k,v])=>`<button class="day" onclick="openWorkout('${k}')"><strong>${v.name}</strong><span>${v.desc}</span><small>${v.ex.length} exercícios</small></button>`).join('')}</div><div class="section-title">Dados</div><button class="secondary" onclick="historyScreen()">📈 Histórico e evolução</button><button class="secondary" onclick="settingsScreen()">⚙️ Configurações</button><button class="secondary" onclick="pdfScreen()">📄 Planilha / PDF</button></div>`}
function makeKey(exi,si){return `${current}-${exi}-${si}`};function draft(){db.drafts[current]??={sets:{},exDone:{},cardio:{},start:null};return db.drafts[current]}
function openWorkout(k){current=k;screen='workout';let d=draft();if(!d.start)d.start=Date.now();workStart=d.start;save();renderWorkout()}
function renderWorkout(){let v=DATA[current],d=draft();let elapsed=Math.floor((Date.now()-d.start)/1000);app.innerHTML=`<div class="app">${header(v.name)}<div class="muted">${v.desc} · ${v.mob}</div><div class="total"><div class="muted">Tempo total do treino</div><strong id="totalTime">${fmt(elapsed)}</strong></div>${v.ex.map((ex,i)=>exerciseHTML(ex,i,d)).join('')}<div class="section-title">Cardio do dia</div><div class="card"><div class="fields"><label>Tempo (min)<input id="cardioTime" type="number" min="0" value="${esc(d.cardio.time||'')}"></label><label>Distância (km)<input id="cardioDist" type="number" min="0" step="0.01" value="${esc(d.cardio.dist||'')}"></label></div><div class="fields"><label>Média (km/h)<input id="cardioAvg" type="number" min="0" step="0.1" value="${esc(d.cardio.avg||'')}"></label></div><div class="obs"><label>Observação<textarea id="cardioObs">${esc(d.cardio.obs||'')}</textarea></label></div><button class="secondary" onclick="saveCardio()">💾 Salvar cardio</button></div><button class="finish" onclick="finishWorkout()">✓ Finalizar e salvar treino</button><button class="secondary danger" onclick="cancelWorkout()">Sair sem finalizar</button></div><div class="timer"><div><small>DESCANSO</small><div class="clock" id="clock">${fmt(timer)}</div></div><div class="timer-actions"><button class="mini" onclick="setTimer(45)">45s</button><button class="mini" onclick="setTimer(60)">1m</button><button class="mini" onclick="setTimer(120)">2m</button><button class="mini" onclick="setTimer(180)">3m</button><button class="mini start" onclick="startTimer()">Iniciar</button></div></div>`;setIntervalTotal()}
function exerciseHTML(ex,i,d){let [name,sets,tech]=ex;let done=!!d.exDone[i];return `<div class="card"><div class="exercise-head"><div class="exercise-name">${i+1}. ${esc(name)}</div><span class="badge ${done?'ok':''}">${done?'Concluído':'Pendente'}</span></div>${tech?`<div class="tech">⚡ ${esc(tech)}</div>`:''}${sets.map((s,j)=>{let k=makeKey(i,j),x=d.sets[k]||{};return `<div class="set"><div class="sethead"><div class="settype">${esc(s[0])}</div><div class="meta">${esc(s[1])} série(s) · ${esc(s[2])} reps · ${esc(s[3])}</div></div><div class="fields"><label>REPS FEITAS<input type="number" min="0" inputmode="numeric" value="${esc(x.reps??'') }" onchange="setVal(${i},${j},'reps',this.value)"></label><label>CARGA (KG)<input type="number" min="0" step="0.5" inputmode="decimal" value="${esc(x.kg??'')}" onchange="setVal(${i},${j},'kg',this.value)"></label></div><div class="obs"><label>OBSERVAÇÃO<textarea onchange="setVal(${i},${j},'obs',this.value)">${esc(x.obs||'')}</textarea></label></div><button class="check ${x.done?'done':''}" onclick="toggleSet(${i},${j})">${x.done?'✓ Série concluída':'□ Marcar série concluída'}</button></div>`}).join('')}<button class="secondary" onclick="toggleEx(${i})">${done?'✓ Exercício concluído':'Marcar exercício como concluído'}</button></div>`}
function setVal(i,j,f,v){let d=draft(),k=makeKey(i,j);d.sets[k]??={};d.sets[k][f]=v;save()};function toggleSet(i,j){let d=draft(),k=makeKey(i,j);d.sets[k]??={};d.sets[k].done=!d.sets[k].done;save();renderWorkout();toast(d.sets[k].done?'Série salva':'Série desmarcada')};function toggleEx(i){let d=draft();d.exDone[i]=!d.exDone[i];save();renderWorkout()};function saveCardio(){let d=draft();d.cardio={time:document.getElementById('cardioTime').value,dist:document.getElementById('cardioDist').value,avg:document.getElementById('cardioAvg').value,obs:document.getElementById('cardioObs').value};save();toast('Cardio salvo')}
function finishWorkout(){saveCardio();let d=draft(),v=DATA[current],record={id:uid(),date:new Date().toISOString(),workout:current,name:v.name,duration:Math.floor((Date.now()-d.start)/1000),data:JSON.parse(JSON.stringify(d))};db.history.push(record);delete db.drafts[current];save();clearInterval(timerId);toast('Treino salvo no histórico');setTimeout(home,500)}function cancelWorkout(){if(confirm('Sair? O treino atual ficará salvo como rascunho.')){clearInterval(timerId);home()}}
function setIntervalTotal(){clearInterval(window.totalTimer);window.totalTimer=setInterval(()=>{let d=draft(),el=Math.floor((Date.now()-d.start)/1000),x=document.getElementById('totalTime');if(x)x.textContent=fmt(el)},1000)}
function fmt(n){n=Math.max(0,Math.floor(n));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')};function setTimer(s){clearInterval(timerId);timer=s;let x=document.getElementById('clock');if(x)x.textContent=fmt(timer)}function startTimer(){clearInterval(timerId);if(timer<=0)timer=60;let x=document.getElementById('clock');if(x)x.textContent=fmt(timer);timerId=setInterval(()=>{timer--;let y=document.getElementById('clock');if(y)y.textContent=fmt(timer);if(timer<=0){clearInterval(timerId);navigator.vibrate?.([200,100,200]);alert('⏱️ Descanso terminado! Volte ao treino.')}},1000)}
function historyScreen(){screen='history';app.innerHTML=`<div class="app">${header('Histórico')}${db.history.length?db.history.slice().reverse().map(r=>{let d=new Date(r.date);return `<div class="history-item"><div class="row"><strong>${r.name}</strong><span class="pill">${d.toLocaleDateString('pt-BR')} ${d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}</span></div><div class="muted">Duração: ${fmt(r.duration)}</div><button class="secondary" onclick="viewRecord('${r.id}')">Ver treino completo</button></div>`}).join(''):'<div class="empty">Ainda não há treinos finalizados.</div>'}</div>`}
function viewRecord(id){let r=db.history.find(x=>x.id===id),v=DATA[r.workout];let html=`<div class="app">${header('Registro do treino')}<div class="muted">${new Date(r.date).toLocaleString('pt-BR')} · duração ${fmt(r.duration)}</div>`;v.ex.forEach((ex,i)=>{html+=`<div class="card"><div class="exercise-name">${i+1}. ${esc(ex[0])}</div>${ex[1].map((s,j)=>{let x=r.data.sets[`${r.workout}-${i}-${j}`]||{};return `<div class="set"><div class="settype">${s[0]}</div><div class="muted">Planejado: ${s[1]} × ${s[2]} · ${s[3]}</div><div style="margin-top:7px"><b>${x.kg||'—'} kg</b> · ${x.reps||'—'} reps ${x.done?'· ✓ concluída':''}</div>${x.obs?`<div class="muted">${esc(x.obs)}</div>`:''}</div>`}).join('')}</div>`});let c=r.data.cardio||{};html+=`<div class="section-title">Cardio</div><div class="card">${c.time||'—'} min · ${c.dist||'—'} km · ${c.avg||'—'} km/h${c.obs?`<div class="muted">${esc(c.obs)}</div>`:''}</div></div>`;app.innerHTML=html}
function settingsScreen(){screen='settings';app.innerHTML=`<div class="app">${header('Configurações')}<p class="muted">Edite nomes, séries, repetições e intervalos. As alterações ficam no aparelho.</p>${Object.entries(DATA).map(([k,v])=>`<div class="card"><div class="row"><strong>${v.name}</strong><span class="pill">${k}</span></div>${v.ex.map((e,i)=>`<div class="edit-ex"><div class="form"><label>Nome<input id="nm-${k}-${i}" value="${esc(e[0])}"></label><button class="secondary" onclick="editName('${k}',${i})">Salvar nome</button><span class="muted">${e[1].length} séries planejadas</span><div class="row"><button class="mini" onclick="addSet('${k}',${i})">+ Série</button><button class="mini danger" onclick="removeExercise('${k}',${i})">Excluir exercício</button></div></div></div>`).join('')}<button class="secondary" onclick="addExercise('${k}')">+ Adicionar exercício</button></div>`).join('')}<button class="secondary" onclick="exportData()">⬇️ Exportar histórico</button><button class="secondary danger" onclick="wipeHistory()">Apagar histórico</button></div>`}
function editName(k,i){DATA[k].ex[i][0]=document.getElementById(`nm-${k}-${i}`).value;persistConfig();toast('Nome alterado')};function addSet(k,i){let type=prompt('Tipo da série (Aquecimento, Ajuste ou Trabalho):','Trabalho');if(!type)return;let qty=prompt('Quantidade de séries:','1');let reps=prompt('Faixa de repetições:','8–12');let rest=prompt('Intervalo:','2 min');DATA[k].ex[i][1].push([type,qty,reps,rest]);persistConfig();settingsScreen()};function removeExercise(k,i){if(confirm('Excluir este exercício?')){DATA[k].ex.splice(i,1);persistConfig();settingsScreen()}};function addExercise(k){let n=prompt('Nome do novo exercício:');if(!n)return;DATA[k].ex.push([n,[['Trabalho','1','8–12','2 min']]]);persistConfig();toast('Exercício adicionado');settingsScreen()};function wipeHistory(){if(confirm('Apagar todo o histórico?')){db.history=[];save();historyScreen()}}function exportData(){let b=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='treino-pro-historico.json';a.click();URL.revokeObjectURL(u)}
function pdfScreen(){app.innerHTML=`<div class="app">${header('Planilha / PDF')}<div class="pdfbox"><p><b>Planilha original</b></p><p class="muted">O PDF enviado foi incluído no pacote do aplicativo como <code>planilha-original.pdf</code>.</p><a class="secondary" style="display:block;text-align:center;text-decoration:none" href="planilha-original.pdf" target="_blank">Abrir planilha original</a></div><div class="section-title">Carregar outro PDF</div><div class="card"><input type="file" accept="application/pdf" id="pdfInput"><p class="muted">O navegador permite selecionar um PDF do celular para consulta. Ele não é enviado para a internet por este app.</p></div></div>`;document.getElementById('pdfInput').onchange=e=>{let f=e.target.files[0];if(f){let u=URL.createObjectURL(f);window.open(u,'_blank')}}}
function goHome(){clearInterval(window.totalTimer);home()}function goSettings(){settingsScreen()}home();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js');
